[2023-12-21 06:39:08 +0000] [56839] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/b-express/src
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/ubuntu/b-express/src/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/ubuntu/b-express/src/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: src.main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fc3237a00e0>
  on_reload: <function OnReload.on_reload at 0x7fc3237a0220>
  when_ready: <function WhenReady.when_ready at 0x7fc3237a0360>
  pre_fork: <function Prefork.pre_fork at 0x7fc3237a04a0>
  post_fork: <function Postfork.post_fork at 0x7fc3237a05e0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fc3237a0720>
  worker_int: <function WorkerInt.worker_int at 0x7fc3237a0860>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fc3237a09a0>
  pre_exec: <function PreExec.pre_exec at 0x7fc3237a0ae0>
  pre_request: <function PreRequest.pre_request at 0x7fc3237a0c20>
  post_request: <function PostRequest.post_request at 0x7fc3237a0cc0>
  child_exit: <function ChildExit.child_exit at 0x7fc3237a0e00>
  worker_exit: <function WorkerExit.worker_exit at 0x7fc3237a0f40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fc3237a1080>
  on_exit: <function OnExit.on_exit at 0x7fc3237a11c0>
  ssl_context: <function NewSSLContext.ssl_context at 0x7fc3237a13a0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-12-21 06:39:08 +0000] [56839] [INFO] Starting gunicorn 21.2.0
[2023-12-21 06:39:08 +0000] [56839] [DEBUG] Arbiter booted
[2023-12-21 06:39:08 +0000] [56839] [INFO] Listening at: http://127.0.0.1:8000 (56839)
[2023-12-21 06:39:08 +0000] [56839] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-12-21 06:39:08 +0000] [56840] [INFO] Booting worker with pid: 56840
[2023-12-21 06:39:08 +0000] [56840] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'
[2023-12-21 06:39:08 +0000] [56840] [INFO] Worker exiting (pid: 56840)
[2023-12-21 06:39:08 +0000] [56841] [INFO] Booting worker with pid: 56841
[2023-12-21 06:39:09 +0000] [56839] [DEBUG] 2 workers
[2023-12-21 06:39:09 +0000] [56841] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'
[2023-12-21 06:39:09 +0000] [56841] [INFO] Worker exiting (pid: 56841)
[2023-12-21 06:39:09 +0000] [56839] [ERROR] Worker (pid:56840) exited with code 3
[2023-12-21 06:39:09 +0000] [56839] [ERROR] Worker (pid:56841) was sent SIGTERM!
[2023-12-21 06:39:09 +0000] [56839] [ERROR] Shutting down: Master
[2023-12-21 06:39:09 +0000] [56839] [ERROR] Reason: Worker failed to boot.
[2023-12-21 06:40:55 +0000] [56865] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/b-express/src
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/ubuntu/b-express/src/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/ubuntu/b-express/src/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: src.main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fd4cffb00e0>
  on_reload: <function OnReload.on_reload at 0x7fd4cffb0220>
  when_ready: <function WhenReady.when_ready at 0x7fd4cffb0360>
  pre_fork: <function Prefork.pre_fork at 0x7fd4cffb04a0>
  post_fork: <function Postfork.post_fork at 0x7fd4cffb05e0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fd4cffb0720>
  worker_int: <function WorkerInt.worker_int at 0x7fd4cffb0860>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fd4cffb09a0>
  pre_exec: <function PreExec.pre_exec at 0x7fd4cffb0ae0>
  pre_request: <function PreRequest.pre_request at 0x7fd4cffb0c20>
  post_request: <function PostRequest.post_request at 0x7fd4cffb0cc0>
  child_exit: <function ChildExit.child_exit at 0x7fd4cffb0e00>
  worker_exit: <function WorkerExit.worker_exit at 0x7fd4cffb0f40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fd4cffb1080>
  on_exit: <function OnExit.on_exit at 0x7fd4cffb11c0>
  ssl_context: <function NewSSLContext.ssl_context at 0x7fd4cffb13a0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-12-21 06:40:55 +0000] [56865] [INFO] Starting gunicorn 21.2.0
[2023-12-21 06:40:55 +0000] [56865] [DEBUG] Arbiter booted
[2023-12-21 06:40:55 +0000] [56865] [INFO] Listening at: http://127.0.0.1:8000 (56865)
[2023-12-21 06:40:55 +0000] [56865] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-12-21 06:40:55 +0000] [56866] [INFO] Booting worker with pid: 56866
[2023-12-21 06:40:55 +0000] [56866] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'
[2023-12-21 06:40:55 +0000] [56866] [INFO] Worker exiting (pid: 56866)
[2023-12-21 06:40:55 +0000] [56867] [INFO] Booting worker with pid: 56867
[2023-12-21 06:40:55 +0000] [56865] [DEBUG] 2 workers
[2023-12-21 06:40:55 +0000] [56867] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'
[2023-12-21 06:40:55 +0000] [56867] [INFO] Worker exiting (pid: 56867)
[2023-12-21 06:40:55 +0000] [56865] [ERROR] Worker (pid:56866) exited with code 3
[2023-12-21 06:40:55 +0000] [56865] [ERROR] Worker (pid:56867) was sent SIGTERM!
[2023-12-21 06:40:55 +0000] [56865] [ERROR] Shutting down: Master
[2023-12-21 06:40:55 +0000] [56865] [ERROR] Reason: Worker failed to boot.
[2023-12-21 06:41:07 +0000] [56921] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/b-express/src
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/ubuntu/b-express/src/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/ubuntu/b-express/src/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f3ea6be80e0>
  on_reload: <function OnReload.on_reload at 0x7f3ea6be8220>
  when_ready: <function WhenReady.when_ready at 0x7f3ea6be8360>
  pre_fork: <function Prefork.pre_fork at 0x7f3ea6be84a0>
  post_fork: <function Postfork.post_fork at 0x7f3ea6be85e0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f3ea6be8720>
  worker_int: <function WorkerInt.worker_int at 0x7f3ea6be8860>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f3ea6be89a0>
  pre_exec: <function PreExec.pre_exec at 0x7f3ea6be8ae0>
  pre_request: <function PreRequest.pre_request at 0x7f3ea6be8c20>
  post_request: <function PostRequest.post_request at 0x7f3ea6be8cc0>
  child_exit: <function ChildExit.child_exit at 0x7f3ea6be8e00>
  worker_exit: <function WorkerExit.worker_exit at 0x7f3ea6be8f40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f3ea6be9080>
  on_exit: <function OnExit.on_exit at 0x7f3ea6be91c0>
  ssl_context: <function NewSSLContext.ssl_context at 0x7f3ea6be93a0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-12-21 06:41:07 +0000] [56921] [INFO] Starting gunicorn 21.2.0
[2023-12-21 06:41:07 +0000] [56921] [DEBUG] Arbiter booted
[2023-12-21 06:41:07 +0000] [56921] [INFO] Listening at: http://127.0.0.1:8000 (56921)
[2023-12-21 06:41:07 +0000] [56921] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-12-21 06:41:07 +0000] [56923] [INFO] Booting worker with pid: 56923
[2023-12-21 06:41:07 +0000] [56924] [INFO] Booting worker with pid: 56924
[2023-12-21 06:41:07 +0000] [56921] [DEBUG] 2 workers
[2023-12-21 06:41:12 +0000] [56923] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/b-express/src/main.py", line 3, in <module>
    from src.users.router import router as router_users
ModuleNotFoundError: No module named 'src'
[2023-12-21 06:41:12 +0000] [56923] [INFO] Worker exiting (pid: 56923)
[2023-12-21 06:41:12 +0000] [56924] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/b-express/venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/b-express/src/main.py", line 3, in <module>
    from src.users.router import router as router_users
ModuleNotFoundError: No module named 'src'
[2023-12-21 06:41:12 +0000] [56924] [INFO] Worker exiting (pid: 56924)
[2023-12-21 06:41:13 +0000] [56921] [ERROR] Worker (pid:56923) exited with code 3
[2023-12-21 06:41:13 +0000] [56921] [ERROR] Worker (pid:56924) was sent SIGTERM!
[2023-12-21 06:41:13 +0000] [56921] [ERROR] Shutting down: Master
[2023-12-21 06:41:13 +0000] [56921] [ERROR] Reason: Worker failed to boot.
